VERSION 0.8

taplo:
    FROM tamasfe/taplo:latest
    SAVE ARTIFACT /taplo

FORMAT:
    FUNCTION

    ARG FIX="false"

    FROM alpine:latest
    WORKDIR /typed-fields

    # Copy the taplo binary into the container
    COPY +taplo/taplo /usr/local/bin/taplo

    # Copy the source code into the container
    COPY . .

    # Check or fix the formatting of the source code
    IF [ "$FIX" = "true" ]
       RUN taplo fmt
    ELSE
        RUN taplo fmt --check
    END

    # Save changes back to the local filesystem
    IF [ "$FIX" = "true" ]
        SAVE ARTIFACT ./* AS LOCAL .
    END
