[package]
name = "typed-fields"
version = "0.0.0"
edition = "2021"

# Setting the MSRV is only supported from 1.56.0 onwards.
rust-version = "1.56"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
