VERSION 0.8

LINT:
    FUNCTION

    FROM node:alpine
    WORKDIR /typed-fields

    # Install markdownlint
    RUN npm install -g markdownlint-cli

    # Copy the source code into the container
    COPY . .

    # Check the Markdown for linting errors
    RUN markdownlint **/*.md
