VERSION 0.8

LINT:
    FUNCTION

    FROM pipelinecomponents/yamllint:latest
    WORKDIR /typed-fields

    # Copy the source code into the container
    COPY . .

    # Check the YAML files for linting errors
    RUN yamllint .
