---
name: GitHub

"on":
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  labels:
    name: Sync labels
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Sync labels
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
