---
name: Rust

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/rust.yml
            Earthfile
            **/*.rs
            **/*.toml

      - name: Print changed files
        run: |
          for file in ${{ steps.detect-changes.outputs.all_changed_files }}; do
            echo "$file"
          done

  doc:
    name: Build docs
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Compile the documentation
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --org jdno --sat xsmall-amd64-1 +doc

  features:
    name: Test features
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Test combinations of features
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --org jdno --sat xsmall-amd64-1 +features

  lint:
    name: Lint code
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run Clippy
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --org jdno --sat xsmall-amd64-1 +lint

  minimal:
    name: Test minimal versions
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run tests with minimal versions
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --org jdno --sat xsmall-amd64-1 +deps-minimal

  msrv:
    name: MSRV
    runs-on: ubuntu-latest

    strategy:
      matrix:
        msrv: [1.61.0]

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Check code with MSRV
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --org jdno --sat xsmall-amd64-1 +msrv

  style:
    name: Check style
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run Rustfmt
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --ci --org jdno --sat xsmall-amd64-1 +format

  test:
    name: Run tests
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install earthly
        uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.8

      - name: Run tests with test coverage
        env:
          EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
        run: earthly --allow-privileged --org jdno --sat xsmall-amd64-1 --strict +test --SAVE_REPORT=yes

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cobertura.xml
